apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  # namespace: logtest
  labels:
    app: postgres
spec:
  clusterIP: None
  selector:
    app: postgres #this is important to match the label of the pod
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
      name: web