apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: logtest
spec:
  type: ClusterIP
  selector:
    app: postgres #this is important to match the label of the pod
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432