# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hashgenerator-dep
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: hashgenerator
#   template:
#     metadata:
#       labels:
#         app: hashgenerator
#     spec:
#       containers:
#         - name: hashgenerator
#           image: mygenapp
#           imagePullPolicy: IfNotPresent
          # ports:
          #   - containerPort: 5000

apiVersion: v1
kind: Pod
metadata:
  name: hashgenerator
  labels:
    app: hashgenerator
spec:
  containers:
  - image: mygenapp
    name: hashgenerator
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 5000
  restartPolicy: Always