apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: logtest
spec:
  type: LoadBalancer
  selector:
    app: pingpong #this is important to match the label of the pod
  ports:
    - port: 3001
      protocol: TCP
      targetPort: 5000