apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: static-image-claim
      containers:
        - name: todoapp
          image: TODOPROJECT
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "150m"
              memory: "100Mi"
          envFrom:
          - configMapRef:
              name: db-secret-credentials
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files
          ports:
            - containerPort: 5000
        - name: imagegenerator
          image: IMAGEGENERATOR
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: shared-image
            mountPath: /usr/src/app/files