apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-image-claim
  namespace: todotest
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi