apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-dep
  namespace: todotest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      volumes: # Define volume
        - name: shared-image
          persistentVolumeClaim:
            claimName: static-image-claim
      containers:
        - name: todoapp
          image: todoapp-image
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files
          ports:
            - containerPort: 5000
        - name: imagegenerator
          image: imagegenerator-image
          imagePullPolicy: IfNotPresent
          volumeMounts: # Mount volume
          - name: shared-image
            mountPath: /usr/src/app/files