apiVersion: apps/v1
kind: Pod
metadata:
  name: hashgenerator-dep
  labels:
    app: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hashgenerator
  template:
    metadata:
      labels:
        app: hashgenerator
    spec:
      containers:
      - name: hashgenerator
        image: logreader
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
