apiVersion: v1
kind: Pod
metadata:
  name: pingpong1
  labels:
    app: pingpong1
spec:
  containers:
    - name: pingpong
      image: pingpong-image
      imagePullPolicy: IfNotPresent
  restartPolicy: Always