apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - manifests/cronjob.yaml
  - manifests/db-configmap.yaml
  - manifests/deployment.yaml
  - manifests/ingress.yaml
  - manifests/persistentvolume.yaml
  - manifests/persistentvolumeclaim.yaml
  - manifests/postgres-service.yaml
  - manifests/postgres-statefulset.yaml
  - manifests/service.yaml
images:
  - name: TODOPROJECT
    newName: surajkodocker/todo:latest
  - name: IMAGEGENERATOR
    newName: surajkodocker/imagegenerator:latest