apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups: ["", "apps", "example.com"]
  resources: ["pods", "deployments", "greetings"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-role
subjects:
- kind: ServiceAccount
  name: operator-sa
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting-operator
  template:
    metadata:
      labels:
        app: greeting-operator
    spec:
      serviceAccountName: operator-sa
      containers:
      - name: operator
        image: my-registry.localhost:5000/my-operator:latest
        imagePullPolicy: IfNotPresent
