apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput1
  namespace: logtest
  labels:
    app: logoutput1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logoutput
  template:
    metadata:
      labels:
        app: logoutput
    spec:
      containers:
      - name: logoutput
        image: surajkodocker/logreader:latest
        imagePullPolicy: IfNotPresent
        envFrom:
          - configMapRef:
              name: db-secret-credentials
      restartPolicy: Always