name: Release application

on:
  push:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: suraj-test-gke
  GKE_ZONE: us-west1-b
  IMAGE: dwk-environments

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./exercises/ex-3-03-Pingpong-GKE-GitHub-Actions

    steps:
      - name: Working Dir
        run: ls

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}
          export_default_credentials: true

      - name: Auth docker
        run: gcloud --quiet auth configure-docker

      - name: Check goolge cloud access
        run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Deploy
        run: |-
          kubectl create namespace logtest
          kustomize build . | kubectl apply -f -
          kubectl rollout status deployment pingpong1
          kubectl get services -o wide